### ISSUE TITLE
Garbage collection

### ISSUE THREAD

**Issue by Enteee** [Enteee/EtherFlows#4]
These days it can happen that a packet is beeing processed by multiple flow workers. This happens because a swtich brodacasts packets with destination MAC to all switchports. We've to eliminate duplicated packes in the ES-database.

Idea how we can do this:
1. Buffer one packet and only send packet to the DB when we get an other packet from the same flow. (flowworker.py ++)
2. Smart periodic cleanup on database with a query and delete script. (cronjob like) Delete packets which are dups.

**Comment by Enteee** [comment]
For this it might be smart to produce a hash over the packet beeing stored in ES. So that we can identify duplicates.

**Comment by noeleont** [comment]
I'm going to investigate if the logstash fingerprint filter plugin could be used for this

**Comment by Enteee** [comment]
With: 
39d8863dcfa8571e53211f4fab9c589183b8bca5  
and a couple of commits before I added flow buffering before writing.

The logic works as follows:
1. The flowworker receives a packet of a new flow
2. The flowworker buffers the packet (does not write it to stdout)
3. The flowworker responds with an ack frame
4. The flowworker buffers all following packets until the lenght of the flow (last packet timestamp - first packet timestamp) is longer tha a given threshold (-l option)
5. The flowworker writes all buffered packets of the flow to stdout
6. The flowworker writes all following packets of this flow to stdout also sends an ack packet

also:
1. Before each packet received the flowworker checks if a flow is not expired:

``` python
    def not_expired(self):
        return self.__newest_frame_time > Flow.newest_overall_frame_time - args.flow_buffer_time
```

This new flowworker has the following implications:
- We can not see flows which are shorter that the threshold (-l option)
- Flow switching can happen if there is no packet for the configured mac aging time on the switches

Thus:
- You should have the same MAC address aging time configured on all the switches.

I'm currently verifying of the logic does what it is supposed to do. First results look promising: I don't have that much flow switching anymore. But I can still see flows which were switched: I've to further investigate them. Maybe incresing the -l option to 10s will help.

**Comment by Enteee** [comment]
the described solution solves the issue.
