### ISSUE TITLE
Filter alert

### ISSUE THREAD

**Issue by Enteee** [Enteee/EtherFlows#5]
The idea is to write a packet filter for logstash which operates on json data.
The following configuration explains what this filter plugin does:

```
filter { 
     jqfilter {
         filter => [
             ' Json query string ' , rule uuid
         ]
         target => "field name"
     }
}
```

this plugin matches the Json query string against the json representation of the event and if matched adds the rule uuid to the field specified with target.

**Comment by Enteee** [comment]
possible query languages:
http://stackoverflow.com/questions/777455/is-there-a-query-language-for-json

**Comment by noeleont** [comment]
logstash json filter plugin is integrated
